### ISSUE TITLE
Laps enabled even in "LapsAvailable false" races

### ISSUE THREAD

**Issue by GennosukeDono** [oldnapalm/CommunityRaces#10]
Just another bug report: as the title says, if you enable more than one lap in the races that allow that in their xml file, races that aren't supposed to have more than one will use the last value you used.

To fix this, you have to find a race with laps and set the value to "1" or alt+tab out of the game to change it in the mod xml.

**Comment by oldnapalm** [comment]
Thanks, fixed in https://github.com/oldnapalm/CommunityRaces/commit/5b8ef58367bf2eae38a84e2fe6c4e7b39a412f54

[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13080530/CommunityRaces.zip)

**Comment by GennosukeDono** [comment]
> Thanks, fixed in [5b8ef58](https://github.com/oldnapalm/CommunityRaces/commit/5b8ef58367bf2eae38a84e2fe6c4e7b39a412f54)
> 
> [CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13080530/CommunityRaces.zip)

Just tried it, amazing.

Thanks to you.
