### ISSUE TITLE
Use your own vehicle on races

### ISSUE THREAD

**Issue by CJdaMan** [oldnapalm/CommunityRaces#12]
Could you please add the option to use your own vehicle in the races? It doesn't even have to modify existing race xml files, just an entry in the ini file.

That way you could preserve the races meant for specific vehicles while giving the player the option top use another. Also, that would 100% solve the point of not being able to use custom or mod-added vehicles.

It doesn't need to be anything fancy, just a checkbox to use your vehicle or not if you get to the race on one. 

Thanks you.

**Comment by oldnapalm** [comment]
Please test

[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13256697/CommunityRaces.zip)

You have to start the race (approach the marker and press E) in a vehicle.

I don't have mod vehicles, no idea what will happen. The mod won't touch the vehicle (except on respawn) so I hope it will work.

**Comment by oldnapalm** [comment]
Changed so that if using own vehicle, other racers also have the same vehicle

[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13257581/CommunityRaces.zip)

**Comment by CJdaMan** [comment]
> Please test
> 
> [CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13256697/CommunityRaces.zip)
> 
> You have to start the race (approach the marker and press E) in a vehicle.
> 
> I don't have mod vehicles, no idea what will happen. The mod won't touch the vehicle (except on respawn) so I hope it will work.

I played a lot of races with motorcycles and cars, both vanilla and mod-added, sometimes respawning from the last  and found no rpoblem! I think this works pretty well with no issue, unless there's anything else in particular you need me to try.

**Comment by CJdaMan** [comment]
> Changed so that if using own vehicle, other racers also have the same vehicle
> 
> [CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13257581/CommunityRaces.zip)

Oh, sorry, I haven't tried this one. Would that be an option, or the usual behaviour of the mod if you use your vehicle? Because all racers having the same would be a little boring.

**Comment by oldnapalm** [comment]
Another change then, now if using own vehicle there will be a 1/AvailableVehicles chance of the other racers have the player vehicle.

Please test if it works with addon vehicles

[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13257977/CommunityRaces.zip)

**Comment by CJdaMan** [comment]
> Another change then, now if using own vehicle there will be a 1/AvailableVehicles chance of the other racers have the player vehicle.
> 
> Please test if it works with addon vehicles
> 
> [CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13257977/CommunityRaces.zip)

I'm glad to report it works as intended with modded vehicles, they sometimes get used by the other drivers in the races and the chance is pretty good for it to happen sometimes, but not every time (that'd be predictable and boring).

This would cover the request and doesn't have any issues.

**Comment by oldnapalm** [comment]
Merged in https://github.com/oldnapalm/CommunityRaces/commit/f6b39dffe076401fd338c08a95a63d8d8ce83e4d

Will be included in the next release.
