### ISSUE TITLE
Hotkey to show/hide blips

### ISSUE THREAD

**Issue by CJdaMan** [oldnapalm/CommunityRaces#13]
Just a suggestion. Right now, you need to alt-tab out of the game, change the ini setting for the blips, and then get back in the game and reload the scripts.

It'd be neat to assign a keyboard key in the ini so you can show/hide them on the fly, since, if you have many races installed, normal game blips will mostly dissapear.

**Comment by oldnapalm** [comment]
Please test

[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13266175/CommunityRaces.zip)

You need to set BLIPSKEY in the config file (e.g. `BLIPSKEY = F7`), there's no default key.

**Comment by CJdaMan** [comment]
> Please test
> 
> [CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13266175/CommunityRaces.zip)
> 
> You need to set BLIPSKEY in the config file (e.g. `BLIPSKEY = F7`), there's no default key.

It works perfectly. Changes from disabled to enabled, grouped and disabled again.
