### ISSUE TITLE
No oponents/empty cars at the start of the race

### ISSUE THREAD

**Issue by CJdaMan** [oldnapalm/CommunityRaces#14]
Hello. I'm not sure if it started happening since the latest version or If i didn't catch it before, but sometimes the races start either with some (or all) vehicles empty, or with no adversaries at all.

It SEEMS the problem presents more often if you select No Traffic in the menu, but it also happens without the option ticked.

**Comment by oldnapalm** [comment]
The only thing that changed when creating opponents is that now, if you enter the race with your own vehicle, there's a chance of the opponents have the same vehicle.

I can think of two possibilities, PedCapacity exceeded (never happened to me) or the ped being deleted when the vehicle is created at the same position.

This test version will create the ped at a slightly different position than the vehicle and display a notification if it fails to create a ped.

[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13468128/CommunityRaces.zip)

**Comment by oldnapalm** [comment]
I can't reproduce this issue. Reopen if/when you can test and provide feedback.
