### ISSUE TITLE
Blips

### ISSUE THREAD

**Issue by Brandomanmods** [oldnapalm/CommunityRaces#2]
Requesting no blip version/ini option to turn off map blips for compatibility with other mods that add blips to the maps.

**Comment by Brandomanmods** [comment]
In addition, an ini option for the races to disappear (both markers and blips) once the race is completed would also be desirable.  Would feel more like they were part of the vanilla game that way.

**Comment by oldnapalm** [comment]
Added the blips option in the ini file. The other request needs more investigation, currently the mod doesn't keep track of race completion (position), the only data saved is the replay of the best ride (for racing against ghost).

[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/7260499/CommunityRaces.zip)

This version also includes a radio station option (#3).
