### ISSUE TITLE
Update Newtonsoft to latest version

### ISSUE THREAD

**Issue by Hydraxonn** [oldnapalm/CommunityRaces#4]
Basically title. Mod uses old version of Newtonsoft, making it incompatible with PlayerCompanion, FoodShops, and some others. Thanks for looking into this!

**Comment by oldnapalm** [comment]
I believe it doesn't need any change in the code, just rebuild using the latest library.

Can you try this?
[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/7322812/CommunityRaces.zip)

**Comment by Hydraxonn** [comment]
Yep, this works. Excellent, thanks! Out of curiosity, I remember GTA CoOp needing the same old Newtonsoft, is that stilll the case? and if so, would updating it's newtonsoft be just as easy? thanks again!

**Comment by oldnapalm** [comment]
Need to try, it may work with a rebuild but may need to adapt the code.

Please leave this issue open for now, I will close it after I add a new release.
