### ISSUE TITLE
Wanted level on racing

### ISSUE THREAD

**Issue by GennosukeDono** [oldnapalm/CommunityRaces#9]
It'd be neat to have an option to toggle a % chance of getting a wanted level when a race starts or after a determinated time has elapsed.

**Comment by oldnapalm** [comment]
For now I changed the wanted option from bool to int (https://github.com/oldnapalm/CommunityRaces/commit/8da88e9f9c0a0f4d1ab3e01d6b5c3a5872b9c673), try it

[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13035190/CommunityRaces.zip)

I can make it more elaborated if you describe with more details.

**Comment by GennosukeDono** [comment]
> For now I changed the wanted option from bool to int ([8da88e9](https://github.com/oldnapalm/CommunityRaces/commit/8da88e9f9c0a0f4d1ab3e01d6b5c3a5872b9c673)), try it
> 
> [CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13035190/CommunityRaces.zip)
> 
> I can make it more elaborated if you describe with more details.

Sorry, I just had time to test until today, had a lot of fun and it worked pretty well. If I may, since you offered to listen, I may have some suggestions that would be great if they are possible:

1) Make it so the wanted level works as a % chance (maybe configurable) at the start of the race, not a 100% chance.

2) If it didn't trigger at the startm maybe make another check every X seconds into the race (maybe configurable).

3) The user decides the max wanted level attainable by this method.

4) It could work as a normal wanted level, it can increase if you kill cops duting the race. I noticed the version you uploaded don't allow the wanted level to increase no matter what you do.

5) The wanted level persist after the race even if you select "Return".

Thanks for your efforts!

**Comment by oldnapalm** [comment]
4 is probably because WantedLevel was being set every frame instead of only on race start, should be fixed in https://github.com/oldnapalm/CommunityRaces/commit/fef5b01741bc3ebb50dab4cb73d38198df5f5912

[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13064487/CommunityRaces.zip)

I will look into the other suggestions when I have more time, need to think a way to implement at least some of them without adding many options regarding wanted level, because it's not the main focus of the mod.

**Comment by GennosukeDono** [comment]
> 4 is probably because WantedLevel was being set every frame instead of only on race start, should be fixed in [fef5b01](https://github.com/oldnapalm/CommunityRaces/commit/fef5b01741bc3ebb50dab4cb73d38198df5f5912)
> 
> [CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13064487/CommunityRaces.zip)
> 
> I will look into the other suggestions when I have more time, need to think a way to implement at least some of them without adding many options regarding wanted level, because it's not the main focus of the mod.

Thanks! About the suggestions, #1 and #3 would be great and enough if you consider them to be good for the mod, of course.

**Comment by oldnapalm** [comment]
Added the options check interval (seconds) and probability (percent) in the INI file, you can try and suggest good default values (https://github.com/oldnapalm/CommunityRaces/commit/728a84d6153e6a0d80c8bbb6e185b758782ea409)

For now the defaults are

```
WANTEDCHECKINTERVAL = 10
WANTEDPROBABILITY = 20
```

[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13170107/CommunityRaces.zip)

**Comment by GennosukeDono** [comment]
> Added the options check interval (seconds) and probability (percent) in the INI file, you can try and suggest good default values ([728a84d](https://github.com/oldnapalm/CommunityRaces/commit/728a84d6153e6a0d80c8bbb6e185b758782ea409))
> 
> For now the defaults are
> 
> ```
> WANTEDCHECKINTERVAL = 10
> WANTEDPROBABILITY = 20
> ```
> 
> [CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/13170107/CommunityRaces.zip)

So sorry for the delay. I just did a quick test, but couldn't find a difference and my ini file did not have any aditional line. I ran a long race with wanted level at 0, as I understand, the game should have made a check every 10 seconds and the new lines should have appeared in my ini, am I correct?

**Comment by oldnapalm** [comment]
The options won't appear in the ini, you have to add them manually or download the new file from https://raw.githubusercontent.com/oldnapalm/CommunityRaces/main/CommunityRaces.ini

Although, the default values should have been used. You also need to set a wanted level higher than zero in the race menu.

**Comment by GennosukeDono** [comment]
> The options won't appear in the ini, you have to add them manually or download the new file from https://raw.githubusercontent.com/oldnapalm/CommunityRaces/main/CommunityRaces.ini
> 
> Although, the default values should have been used. You also need to set a wanted level higher than zero in the race menu.

Good day. I tested on a good amount or races, and the setting works as intended. I tried many combinations of chance/time, and the results seems to be consistent and add a good amount of variety. Also, the wanted level indicated in the ini is the one the game uses correctly.

It just works. :p

**Comment by oldnapalm** [comment]
Thanks for testing and reporting.

Changes were already merged in https://github.com/oldnapalm/CommunityRaces/commit/728a84d6153e6a0d80c8bbb6e185b758782ea409 and will be included in the next release.
